services:
  paramount:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Paramount
    environment:
      - BASE_URL=http://localhost:3002
      - KEY_SECRET=[random]
      - MFP_URL=
      - MFP_PASS=
    ports:
      - "3002:3000"
    restart: unless-stopped